version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tms-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./database/database.sqlite:/var/www/database/database.sqlite
    networks:
      - tms-network

  nginx:
    image: nginx:alpine
    container_name: tms-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./database/database.sqlite:/var/www/database/database.sqlite
    command: >
      /bin/sh -c "echo 'server {
          listen 80;
          index index.php index.html;
          root /var/www/public;
          
          # Timeout settings
          fastcgi_read_timeout 300;
          fastcgi_send_timeout 300;
          fastcgi_connect_timeout 300;
          proxy_read_timeout 300;
          proxy_connect_timeout 300;
          proxy_send_timeout 300;
          
          location ~ \.php$ {
              try_files $$uri =404;
              fastcgi_split_path_info ^(.+\.php)(/.+)$;
              fastcgi_pass app:9000;
              fastcgi_index index.php;
              include fastcgi_params;
              fastcgi_param SCRIPT_FILENAME $$document_root$$fastcgi_script_name;
              fastcgi_param PATH_INFO $$fastcgi_path_info;
              
              # PHP-FPM timeout settings
              fastcgi_read_timeout 300;
              fastcgi_send_timeout 300;
              fastcgi_connect_timeout 300;
          }
          location / {
              try_files $$uri $$uri/ /index.php?$$query_string;
              gzip_static on;
          }
      }' > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    networks:
      - tms-network

  db:
    image: mysql:8.0
    container_name: tms-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-tms}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_USER: ${DB_USERNAME:-tms}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - tms-network

networks:
  tms-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
  database:
    driver: local
